### ISSUE TITLE
Cors & fetch errors in console

### ISSUE THREAD

**Issue by scenaristeur** [solid/profile-viewer-tutorial#10]
Wanted to try solid, so i used my little expres server https://github.com/scenaristeur/smag0UiServer
You are in my friends , it's ok, but  clicking at your profile give me some errors in js console : 
Some Cors error

![image](https://user-images.githubusercontent.com/4020744/47609018-9bfe7080-da37-11e8-8673-5f3c6ec666a9.png)

Some Fetch Errors 

![image](https://user-images.githubusercontent.com/4020744/47609027-c05a4d00-da37-11e8-9b97-d627c9230fd9.png)

![image](https://user-images.githubusercontent.com/4020744/47608989-37dbac80-da37-11e8-8a95-344cf4fa94b3.png)

**Comment by RubenVerborgh** [comment]
Thanks for reporting. These errors are normal: the profile viewer is trying to fetch data from the Web, not all websites allow this, hence the errors. The fallback is to display the URL instead.
