### ISSUE TITLE
seems like clone not working?

### ISSUE THREAD

**Issue by TomCJones** [solid/profile-viewer-tutorial#12]
PS C:\Users\rp_to_000\Source\Repos\Solid> git clone git@github.com:solid/profile-viewer-tutorial.git
Cloning into 'profile-viewer-tutorial'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by RubenVerborgh** [comment]
That seems to be an issue with your local configuration rather than this particular repository. Could you confirm that other public repositories are working? It's best to file this with GitHub if it persists.

**Comment by TomCJones** [comment]
yeah - I use GitHub all the day long - no trouble - so I copies the files from the raw view. They don't work, probably because of the imbedded script which is unsafe. I guess I can move it.
