### ISSUE TITLE
Step 9 sample code on https://solid.inrupt.com/docs/app-on-your-lunch-break

### ISSUE THREAD

**Issue by bquinn** [solid/profile-viewer-tutorial#5]
should be `$('#view).click(` instead of `$('#viewer').click(`...

I was switching between grabbing code from the page and from github, the github version refers to `#view` but the code on the page says `#viewer`. 

It's correct from step 10 onwards.

**Comment by RubenVerborgh** [comment]
Thanks, fixed!
