### ISSUE TITLE
rdflib.min.js issue

### ISSUE THREAD

**Issue by edw-nestor** [solid/profile-viewer-tutorial#6]
This file isn't working for me. VSCode lights up with tons of errors. At first glance it looks like a comment forward slash is missing. If I add a forward slash at the very beginning, that handles many of the issues, but not all. I'm trying to complete the lunch tutorial. Thanks.

**Comment by edw-nestor** [comment]
I just cloned the tutorial and all is working. Not sure what I was doing wrong.

**Comment by RubenVerborgh** [comment]
Okay, let us know if you run into more trouble.
