### ISSUE TITLE
consider setting default branch to gh-pages

### ISSUE THREAD

**Issue by melvincarvalho** [solid/profile-viewer-tutorial#8]
Has the benefit of a live demo

Example : https://github.com/melvincarvalho/profile-viewer-tutorial
Demo : https://melvincarvalho.github.io/profile-viewer-tutorial/

Requires

```
git checkout -b gh-pages
git push origin gh-pages
```

Then go to settings->branches and change the default

**Comment by RubenVerborgh** [comment]
Thanks for the suggestion! I configured GitHub to serve from the master branch.

**Comment by RubenVerborgh** [comment]
https://solid.github.io/profile-viewer-tutorial/
