### ISSUE TITLE
local rdflib vs rdflib-0.12.2.min.js

### ISSUE THREAD

**Issue by rimmartin** [solid/profile-viewer-tutorial#9]
Hi,

https://solid.github.io/releases/rdflib.js/rdflib-0.12.2.min.js
is quite different from
https://github.com/solid/profile-viewer-tutorial/blob/master/scripts/rdflib.min.js

What is the most current?  What API documentation? In the image
https://raw.githubusercontent.com/linkeddata/rdflib.js/Documentation/diagrams/rdflib_block_diagram.png
there is for the Fetcher, load, put, refresh, these are not all found in the rdflib's above

**Comment by RubenVerborgh** [comment]
> [solid.github.io/releases/rdflib.js/rdflib-0.12.2.min.js](https://solid.github.io/releases/rdflib.js/rdflib-0.12.2.min.js)
> is quite different from
> [/scripts/rdflib.min.js@`master`](https://github.com/solid/profile-viewer-tutorial/blob/master/scripts/rdflib.min.js)

Yes, we recently upgraded the build system on rdflib, so the diff is huge (but the actual code differences are minimal).

> What is the most current?

rdflib-0.12.2.min.js

This repository was built some time ago, and includes and older version.

> What API documentation?

This is the best guide: https://solid.inrupt.com/docs/manipulating-ld-with-rdflib
